### ISSUE TITLE
Adding GitHub Actions to have CI

### ISSUE THREAD

**Issue by szabgab** [totalhack/zillion#13]
I am using [Pydigger](https://pydigger.com/) to monitor recent uploads to PyPI that don't have any Continuous Integration (CI) system configured.  A CI system can greatly improve the development experience by providing quick feedback to the developers and contributors, even for a toy or experimental project.  As my contribution to open source (see [why](https://osdc.code-maven.com/why))I try to contribute a simple CI configuration to these projects to get started. 

I've started to work on adding GitHub Action, I am going to report the issues here as I encounter them.

**Comment by szabgab** [comment]
```
ImportError while loading conftest '/__w/zillion/zillion/tests/conftest.py'.
conftest.py:4: in <module>
    from .test_utils import *
test_utils.py:22: in <module>
    from zillion.configs import (
../zillion/__init__.py:15: in <module>
    from .configs import (
../zillion/configs.py:1168: in <module>
    class ZillionInfo(MappingMixin):
../zillion/configs.py:1189: in ZillionInfo
    @initializer
/usr/local/lib/python3.11/site-packages/tlbx/object_utils.py:73: in initializer
    names, varargs, keywords, defaults = inspect.getargspec(func)
E   AttributeError: module 'inspect' has no attribute 'getargspec'
Error: Process completed with exit code 4.
```

See https://github.com/szabgab/zillion/actions/runs/4858325131/jobs/8659631749#step:6:21

**Comment by totalhack** [comment]
Thanks, it seems there is a 3.11 compatibility issue in an underlying library. I'll take a look.

**Comment by szabgab** [comment]
Thanks, switching to 3.10 solved this, now I need to configure the dbs. I'll update when there is progress.

**Comment by totalhack** [comment]
Hey @szabgab, anything I can do to help?

**Comment by szabgab** [comment]
I got busy with other things. I'll give it a go now.
